using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SpecOps.Generators;

[Generator]
public class SpecificationExtensionsGenerator : IIncrementalGenerator
{
    private const string SpecificationFullName = "SpecOps.Specification";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var specs = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) => IsCandidateClass(node),
            transform: static (ctx, _) => GetSpecInfo(ctx))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value);

        var grouped = specs.Collect();

        context.RegisterSourceOutput(grouped, static (spc, specInfos) => Execute(spc, specInfos));
    }

    private static bool IsCandidateClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax cds
            && cds.BaseList is not null
            && !cds.Modifiers.Any(SyntaxKind.AbstractKeyword);
    }

    private static SpecInfo? GetSpecInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl);
        if (symbol is null || symbol.IsAbstract || symbol.IsGenericType)
            return null;

        var entityType = GetSpecificationEntityType(symbol);
        if (entityType is null)
            return null;

        var parameters = GetConstructorParameters(symbol);
        var ns = symbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : symbol.ContainingNamespace.ToDisplayString();

        return new SpecInfo(
            ClassName: symbol.Name,
            Namespace: ns,
            EntityType: entityType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            Parameters: parameters);
    }

    private static INamedTypeSymbol? GetSpecificationEntityType(INamedTypeSymbol symbol)
    {
        var current = symbol.BaseType;
        while (current is not null)
        {
            if (current.IsGenericType
                && current.ConstructedFrom.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                    .StartsWith("global::" + SpecificationFullName + "<"))
            {
                return (INamedTypeSymbol)current.TypeArguments[0];
            }
            current = current.BaseType;
        }
        return null;
    }

    private static ImmutableArray<ParameterInfo> GetConstructorParameters(INamedTypeSymbol symbol)
    {
        // Prefer the primary constructor (the one matching the class declaration),
        // which is typically the one with parameters. If none, take the first with params.
        var ctors = symbol.Constructors
            .Where(c => !c.IsImplicitlyDeclared && !c.IsStatic)
            .OrderByDescending(c => c.Parameters.Length)
            .ToArray();

        var ctor = ctors.Length > 0 ? ctors[0] : null;
        if (ctor is null || ctor.Parameters.Length == 0)
            return ImmutableArray<ParameterInfo>.Empty;

        return ctor.Parameters
            .Select(p => new ParameterInfo(
                Name: p.Name,
                Type: p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)))
            .ToImmutableArray();
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<SpecInfo> specs)
    {
        if (specs.IsDefaultOrEmpty)
            return;

        var grouped = specs
            .GroupBy(s => s.Namespace ?? "")
            .ToArray();

        foreach (var group in grouped)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();

            var ns = group.Key;
            if (ns.Length > 0)
            {
                sb.AppendLine($"namespace {ns};");
                sb.AppendLine();
            }

            sb.AppendLine("public static partial class Specs");
            sb.AppendLine("{");

            foreach (var spec in group)
            {
                var paramList = string.Join(", ", spec.Parameters.Select(p => $"{p.Type} {p.Name}"));
                var argList = string.Join(", ", spec.Parameters.Select(p => p.Name));
                var specType = $"global::SpecOps.Specification<{spec.EntityType}>";

                // Factory method
                sb.AppendLine($"    public static {specType} {spec.ClassName}({paramList})");
                sb.AppendLine($"        => new {spec.ClassName}({argList});");
                sb.AppendLine();

                // Extension method for SpecChain
                var chainParam = $"this global::SpecOps.SpecChain<{spec.EntityType}> chain";
                var extParamList = paramList.Length > 0 ? $"{chainParam}, {paramList}" : chainParam;

                sb.AppendLine($"    public static {specType} {spec.ClassName}({extParamList})");
                sb.AppendLine($"        => chain.Combine(new {spec.ClassName}({argList}));");
                sb.AppendLine();
            }

            sb.AppendLine("}");

            var hintName = ns.Length > 0 ? $"{ns}.Specs.g.cs" : "Specs.g.cs";
            context.AddSource(hintName, sb.ToString());
        }
    }

    private readonly record struct SpecInfo(
        string ClassName,
        string? Namespace,
        string EntityType,
        ImmutableArray<ParameterInfo> Parameters);

    private readonly record struct ParameterInfo(
        string Name,
        string Type);
}
